# Generated by Django 2.2.7 on 2019-11-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20191117_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('correct_option', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Quiz')),
            ],
        ),
    ]
